version: 4.0.1.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - Llvm.Libs

image: Visual Studio 2017

skip_commits:
  files:
    - '**\*.md'

environment:
  BuildNugetUser:
    secure: f6wD21gZoNIxzurB9sZmRKGWa9Dpj4BjUdPqOmj7WqM=
  BuildNugetPassword:
    secure: C4Z+91Dp0oltWIm1cjf5Lw==

nuget:
  disable_publish_on_pr: true
  account_feed: true
  project_feed: true

init:
  - nuget source update -Name AppVeyorAccountFeed -UserName %BuildNugetUser% -Password %BuildNugetPassword%

build_script:
  - nuget install Llvm.Libs -Version 4.0.1 -NoCache -NonInteractive -Source https://ci.appveyor.com/nuget/telliam -OutputDirectory pkginstall

artifacts:
  - path: pkginstall\**\Llvm.Libs.*.nupkg
